### ISSUE TITLE
Generate benchmarks to compare existing EventsExecutor with EventsCBGExecutor

### ISSUE THREAD

**Issue by skyegalaxy** [ros2/ros2#1746]
Use the iRobot benchmark tools to compare the two events executor implementations.

Relates to https://github.com/ros2/ros2/issues/1730

**Comment by skyegalaxy** [comment]
@alsora @jmachowinski 

I wanted to give a quick update on running these benchmarks ahead of the client library working group this friday. I got our benchmark container running with ros2 rolling alongside `cm_executors`. I added `EventsCBGExecutor` as one of the available executors to run the benchmarks with (enabled with `--executor 4`) and set it to just use one thread for now for a somewhat more direct comparison with `rclcpp::experimental::EventsExecutor`. While I'm able to generate some partial metrics, so far I've encountered two issues that have prevented me from completing an entire run of our benchmark suite with `EventsCBGExecutor`:

(I wasn't sure if I should file these as issues under `cm_executors` or not, but I wanted to start by documenting them somewhere as we'll definitely want to keep them in mind as we bring `EventsCBGExecutor` into `rclcpp` as the new `EventsExecutor`)

1. When running one of the action client / server benchmarks with `EventsCBGExecutor`, the program freezes up on shutdown. I ran an isolated example in gdb, ctrl+c'd when it froze, and got the following backtrace which appears to show the freeze starting from `CBGScheduler::release_all_worker_threads`. You can see the full command and backtrace [here](https://gist.github.com/skyegalaxy/a7c21b378450f9f898dc118cbd0ca336).

2: When running single process pub/sub benchmarks with `EventsCBGExecutor`, the program consistently crashes with larger topologies, in particular `50_topics_2000_hz`. Check out the stdout and backtrace [here](https://gist.github.com/skyegalaxy/5aac6469eb802b94a0f1f43580765692). 

In the meantime, I'll try to collect what results I have right now and compare with `rclcpp::experimental::EventsExecutor` for friday.

**Comment by jmachowinski** [comment]
That sounds odd, I'll look into it. Can you give me details on the ros version you used ? 
The freeze bug was introduced by some internal changes I did, and should be solved if you use the correct version of rclcpp.
https://github.com/ros2/rclcpp/commit/7ebc9e4cae34483c8d0510b650032a80ae84fd92 this commit should have fixed it in particular. 

I'll check 2 and try to reproduce it.

**Comment by jmachowinski** [comment]
@skyegalaxy Were would I find the topology 50_topics_2000_hz. It does not seem to be part of the repo found here : https://github.com/irobot-ros/ros2-performance/

**Comment by jmachowinski** [comment]
https://pastebin.com/UctVR2Yj

Result on my machine (AMD Ryzen 9 9900X)

Events Executor:
System total:
received_msgs  mean_us   late_msgs late_perc too_late_msgs  too_late_perc  lost_msgs lost_perc 
6126           16        0         0         0              0              0         0 

CBG SingleThread:
System total:
received_msgs  mean_us   late_msgs late_perc too_late_msgs  too_late_perc  lost_msgs lost_perc 
6126           18        0         0         0              0              0         0    

CBG MultiThread:
System total:
received_msgs  mean_us   late_msgs late_perc too_late_msgs  too_late_perc  lost_msgs lost_perc 
6132           35        0         0         0              0              0         0      

SingleThreadedExecutor:
System total:
received_msgs  mean_us   late_msgs late_perc too_late_msgs  too_late_perc  lost_msgs lost_perc 
6126           28        0         0         0              0              0         0  

MultiThreadedExecutor:
System total:
received_msgs  mean_us   late_msgs late_perc too_late_msgs  too_late_perc  lost_msgs lost_perc 
6125           31        0         0         0              0              0         0    

I don't know if these numbers are really meaningful. Even with the performance CPU governor, running 3 times in a row I get numbers all over the place : 
System total:
received_msgs  mean_us   late_msgs late_perc too_late_msgs  too_late_perc  lost_msgs lost_perc 
6125           21        0         0         0              0              0         0     

System total:
received_msgs  mean_us   late_msgs late_perc too_late_msgs  too_late_perc  lost_msgs lost_perc 
6125           28        0         0         0              0              0         0 

System total:
received_msgs  mean_us   late_msgs late_perc too_late_msgs  too_late_perc  lost_msgs lost_perc 
6125           32        0         0         0              0              0         0

**Comment by jmachowinski** [comment]
No crashes or hangs on my test setup...

**Comment by skyegalaxy** [comment]
@jmachowinski I was doing these benchmarks with ROS rolling. The topology was a newer one we made on top of some other tooling that builds on top of `ros2-performance`, including the container environment and data analysis tools, which we're still having conversations around open-sourcing in its entirety. 

ROS2 version: commit `380866b3380d74199d24b190bea24d51ab1f3ba0 (HEAD -> rolling, tag: 30.1.1, origin/rolling, origin/HEAD)`
cm_executors version: commit `da08774032db07471b027e7c43d0ffdbbb1cb7b8 (HEAD -> kilted, origin/kilted)` (I tried compiling with master but it failed against rolling) 
Topology: https://gist.github.com/skyegalaxy/66a1c457ed1dfc48b130088a8e34f9ba

This was run on [my x86 developer laptop](https://gist.github.com/skyegalaxy/bb3a6cb144dba4444763d1eb2d44c4e7), inside the upstream `osrf/ros` rolling container. `ros2-performance`, `rclcpp`, and `cm_executors` were built in a workspace inside the container with debug flags.

**Comment by jmachowinski** [comment]
I just added two new branches to the cm_executor package for rolling and jazzy.

**Comment by jmachowinski** [comment]
I found a memory violation in case the shutdown callback was called. This is fixed now.
@skyegalaxy does that fix the problem for your ?

**Comment by skyegalaxy** [comment]
@jmachowinski unfortunately after doing a clean rebuild of my workspace with the top of your rolling branch (and top of rclcpp and rcl rolling from today) I'm still getting a crash[ with a similar backtrace](https://gist.github.com/skyegalaxy/4d14dc6bd2b8a91590a1763e7dac516b) to the original 50 topic 2000hz run. I ran both scenarios again multiple times just to be sure, and interestingly, sometimes the benchmark works out fine and it'll exit without problems, but the rest of the time it's the same crash. 
Similarly, the [actions freeze](https://gist.github.com/skyegalaxy/d51080bd8c5f031133305a9cde6eacf4) is still happening about as often. Sometimes the thread exits on its own and other times it hangs. 
I wonder if the sporadic nature of both of these issues indicates a common source?

**Comment by jmachowinski** [comment]
Does running this in valgrind give any clue to what might be going on ?

**Comment by skyegalaxy** [comment]
For the actions freeze, running with valgrind gets us a `Access not within mapped region` warning when I'm able to repro the freeze: https://gist.github.com/skyegalaxy/3b40c8d51ca1d874270825041f2cda38

For the 50 topic 2000 hz crash, I'm unable to reproduce it inside valgrind after trying a bunch of times, although interestingly enough, I do consistently get this warning about a segment overflow in the main thread when creating all the subscribers: 

```
[INFO] [1758060862.340137436] [sub_node_sp]: Subscription to test_20 created
[INFO] [1758060862.357041068] [sub_node_sp]: Subscription to test_21 created
[INFO] [1758060862.374077164] [sub_node_sp]: Subscription to test_22 created
[INFO] [1758060862.394722869] [sub_node_sp]: Subscription to test_23 created
[INFO] [1758060862.412498078] [sub_node_sp]: Subscription to test_24 created
==78574== brk segment overflow in thread #1: can't grow to 0x4853000
==78574== (see section Limitations in user manual)
==78574== NOTE: further instances of this message will not be shown
[INFO] [1758060862.431623809] [sub_node_sp]: Subscription to test_25 created
[INFO] [1758060862.449108697] [sub_node_sp]: Subscription to test_26 created
[INFO] [1758060862.466273473] [sub_node_sp]: Subscription to test_27 created
[INFO] [1758060862.484011720] [sub_node_sp]: Subscription to test_28 created
[INFO] [1758060862.500846656] [sub_node_sp]: Subscription to test_29 created
[INFO] [1758060862.518429932] [sub_node_sp]: Subscription to test_30 created
```

I've attached the callgrind files if you wanna give them a look in `kcachegrind`. 

[actions_freeze.tar.gz](https://github.com/user-attachments/files/22372477/actions_freeze.tar.gz)
[50_topics_2000hz.tar.gz](https://github.com/user-attachments/files/22372476/50_topics_2000hz.tar.gz)

**Comment by skyegalaxy** [comment]
Forgot to mention: for the actions freeze, the topmost thread (whether run through valgrind or just the program itself) enters a zombie state that prevents the thread itself from dying, and the only thing that kills it is sending a `SIGKILL` to any of the child threads 

<img width="920" height="204" alt="Image" src="https://github.com/user-attachments/assets/3d94d815-ebd4-488d-bb2d-8f601441823b" />

**Comment by jmachowinski** [comment]
I think we need a new approach to debugging this. I can not reproduce the problem. 
For now, I set up a LXC container with ubuntu 24.04 with a fresh rolling source install also containing the cm_executor and the ros2-performance package from my fork. 
Using this setup and running 'valgrind --trace-children=yes ./irobot_benchmark -x 4 topology/white_mountain.json' I see a bunch of unrelated errors (Mismatched new/delete size value: 1 from rcl) but no error originating from the our executor and no crashes. 

@skyegalaxy can you setup the same test container and verify that you don't get any errors as well, so that we can establish a common ground ? 

Note: The Mismatched new/delete size value: 1 from rcl are not present under Ubuntu 22.04 and rolling and I'm currently investigating the source of these.

**Comment by skyegalaxy** [comment]
I got caught up with other work stuff yesterday but I'll see if I can find time to set up the lxc container either today or tomorrow. In the meantime, I've generated a large set of processed benchmark data for both `EventsCBGExecutor` and `EventsExecutor` which I'll aim to post here by EOD. (It took me a while because the full suite of benchmarks takes ~3 hours since we have lots of topologies and I ran them for fastdds, cyclonedds, and zenoh, multiple times each)

**Comment by skyegalaxy** [comment]
My analysis / writeup of the data I collected is [here](https://gist.github.com/skyegalaxy/71ba2696e6d3a081bdcb0b9fb51a4c71). 

tl;dr: 
- there doesn't appear to be too much of a difference across all the characteristics we tested. EventsExecutor performs slightly better during the long running pub/sub CPU usage test. EventsCBGExecutor performs a bit better on the long running actions CPU usage test. 
- Both executors appear to demonstrate memory leaks in the longer running pub / sub and actions tests. I'm not sure whether this is an issue with the executors themselves, the test, or something else in the client library.

**Comment by skyegalaxy** [comment]
Next steps as a follow-up to the discussion in the client library meeting today:
- [ ] Rerun these benchmarks on more constrained hardware (raspberry pi 4)
- [ ] Run the long running benchmarks demonstrating the memory leaks in valgrind
- [x] Reformat original benchmarks gist into a ROS discourse post for broader discussion
- [x] repro Janosch's lxc setup and rerun the problematic tests we identified earlier to see if it's an issue in other container types

**Comment by skyegalaxy** [comment]
@jmachowinski  - I finally had some time today to set up the LXC container and do a clean rolling build, with cm_executors (rolling) and ros2-performance. I am still able to reproduce the same freezes and crashes as seen in the rolling docker container.

For your convenience, I have pushed my ros2-performance changes that incorporate the new executor as well as the suspect topologies [here](https://github.com/irobot-ros/ros2-performance/tree/smedeiros/benchmark-cbg-executor).

I've also put up a[ brand new gist containing gdb backtraces](https://gist.github.com/skyegalaxy/8df5ff8294510093de5d8127bde746cf) from both tests like before, run from inside my lxc container.

**Comment by skyegalaxy** [comment]
you'll also wanna make sure these benchmarks are being run with sudo/root so that the CPU governor can be set to performance mode. In my case, I simply set up a privileged lxc container which just ran as root (same as the docker container)

**Comment by jmachowinski** [comment]
@skyegalaxy  FYI: I am currently busy at work and did not find time yet to look into this. But it's still in my backlog. And I will be on vacation for the next two weeks...

**Comment by jmachowinski** [comment]
Issues have been fixed upstream
